### ISSUE TITLE
Property 'registerAsync' does not exist on type 'typeof MinioModule'.

### ISSUE THREAD

**Issue by JCH97** [djedlajn/nestjs-minio-client#29]
I've installed version 2.0.0 and I'm getting this error when use MinioModule.registerAsync.

**Comment by rejvban** [comment]
@JCH97 Mind sharing the Nest version and possibly reproduction steps

**Comment by adidaslevy** [comment]
Happens also for `register` method. 
This is my nestjs: 
"@nestjs/core": "^6.7.2",

**Comment by lkaric** [comment]
@adidaslevy Versions > 2 do not support Nestjs versions less then 9.0.0
