### ISSUE TITLE
Error TS2688: Cannot find type definition file for 'minio'.

### ISSUE THREAD

**Issue by Ismoil4432** [djedlajn/nestjs-minio-client#35]
When I install @types/minio with this command:

`yarn add -D @types/minio`

it says:

```
error TS2688: Cannot find type definition file for 'minio'.
  The file is in the program because:
    Entry point for implicit type library 'minio'
```

But when I remove it from packages, it no longer giving error.

**Comment by MoacirCarlos** [comment]
I just got the same error here.

**Comment by lkaric** [comment]
@Ismoil4432 @MoacirCarlos The stub has been deprecated, type definitions now live with the `minio` package itself, updated the docs!
