### ISSUE TITLE
Cannot list files from Minio if file name is not a string

### ISSUE THREAD

**Issue by Dinshaj** [djedlajn/nestjs-minio-client#37]
I am using nestjs-minio-client version 2.1.0.

When I try to list files from Minio, I get an error if the file name is not a string. For example, if the file name is 1234567890, I get the following error:

> `/app/node_modules/minio/dist/main/helpers.js:495
  var asStrName = (objectName || "").replace(/\+/g, ' ');`
  
`TypeError: (objectName || "").replace is not a function
    at sanitizeObjectKey (/app/node_modules/minio/dist/main/helpers.js:495:38)
    at /app/node_modules/minio/dist/main/xml-parsers.js:548:49`
    
The code used to retrieve the data list is presented below.
    
`import { Injectable } from '@nestjs/common';
import { MinioClient } from '@nestjs/minio-client';

@Injectable()
export class MinioService {
  constructor(private readonly minioClient: MinioClient) {}

  async listFiles(): Promise<string[]> {
   const stream = this.minio.client.extensions.listObjectsV2WithMetadata(
           'bucket name',
            '',
            true,
            'directory name'
          );
  }
}`

**Comment by lkaric** [comment]
@Dinshaj Couldn't reproduce the issue, try it with `2.2.0` if it persists, please provide additional reproduction information.

**Comment by lkaric** [comment]
Closing because of no response.
