### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by manuks** [djedlajn/nestjs-minio-client#38]
Can we use node 20.9.0 LTS ? I am getting error as below
`102.3 error minio@7.0.30: The engine "node" is incompatible with this module. Expected version ">8  <=18". Got "20.9.0"`

**Comment by djedlajn** [comment]
I will release new version with updated versioning today.

**Comment by askareija** [comment]
I've got some vulnerabilities all related to minio. I hope you can update version very soon.
![Cuplikan layar dari 2023-10-31 11-42-16](https://github.com/djedlajn/nestjs-minio-client/assets/21377617/7187540e-ba57-43f6-a47c-f3d857fb9912)
![Cuplikan layar dari 2023-10-31 11-42-27](https://github.com/djedlajn/nestjs-minio-client/assets/21377617/c4d4e649-02a0-4bbe-81ed-6fe91d2f8ec2)

**Comment by manuks** [comment]
https://snyk.io/advisor/npm-package/fast-xml-parser and https://snyk.io/advisor/npm-package/browserify-sign shows the issues are fixed.

**Comment by lkaric** [comment]
@manuks @askareija  Should be able to use LTS version with `2.2.0`, also all of the dependencies are updated. Please check and close the issue accordingly.

**Comment by lkaric** [comment]
Closing because of no response.
