### ISSUE TITLE
Typescript definitions need to improve

### ISSUE THREAD

**Issue by hrahimi270** [djedlajn/nestjs-minio-client#6]
Hi.
I installed this package and start using it, and the first thing I faced was Typescript definitions. They are good, but when I want to use my client with this line of code for example `this.minioService.client.putObject`, I only have definitions of `minioService`. Not the client methods.
Look at this image.
![Screen Shot 2020-11-01 at 8 16 19 PM](https://user-images.githubusercontent.com/38007163/97808940-1db8b280-1c7f-11eb-809e-75ca5ec537d1.png)

But, when I want to see the methods available to my client, I don't have them.
![Screen Shot 2020-11-01 at 8 16 49 PM](https://user-images.githubusercontent.com/38007163/97808956-3032ec00-1c7f-11eb-8200-c0af891dbdb8.png)

I hope I have conveyed what I mean (:
Thanks.

**Comment by djedlajn** [comment]
Yeah, mistake on my part. Will push a patch for this sometime tomorrow.

**Comment by hrahimi270** [comment]
Will appreciate that.

**Comment by hrahimi270** [comment]
Hi @djedlajn, any updates on it?

**Comment by harry75369** [comment]
Just install '@types/minio' in your own project and there will be hints.

**Comment by djedlajn** [comment]
Should work without the need to install @types in `v1.2.0`.
